SELECT * FROM BRAND;
SELECT * FROM SALARY_HISTORY;
SELECT * FROM PRODUCT;
select * from EMPLOYEE;
SELECT * FROM CUSTOMER;
SELECT * FROM INVOICE;
SELECT * FROM DEPARTMENT;
SELECT * FROM LINE;
SELECT * FROM SUPPLIES;

---- query 1 ---
SELECT e.EMP_NUM,e.EMP_FNAME,e.EMP_LNAME,s.SAL_AMOUNT
FROM EMPLOYEE e 
JOIN SALARY_HISTORY s ON s.EMP_NUM = e.EMP_NUM
WHERE e.DEPT_NUM = 300 AND s.SAL_END IS NULL
ORDER BY 4 DESC;

--update SALARY_HISTORY set sal_end =null where sal_end=TO_DATE('01/JAN/1900 00:00:00','dd/mon/yyyy HH24:MI:SS');

---- query 2 -----
SELECT e.EMP_NUM,e.EMP_FNAME,e.EMP_LNAME,s.SAL_AMOUNT
FROM EMPLOYEE e 
JOIN SALARY_HISTORY s ON s.EMP_NUM = e.EMP_NUM
WHERE s.SAL_FROM = e.EMP_HIREDATE
ORDER BY 1 ;

--- query 3 ---

SELECT SEALER.INV_NUM,SEALER.LINE_NUM,SEALER.PROD_SKU,SEALER.PROD_DESCRIPT,SEALER.BRAND_ID
FROM 
(SELECT l1.INV_NUM,l1.LINE_NUM,l1.PROD_SKU,p1.PROD_DESCRIPT,p1.BRAND_ID 
FROM LINE l1,PRODUCT p1
WHERE l1.PROD_SKU = p1.PROD_SKU
AND p1.PROD_CATEGORY = 'SEALER'
) SEALER,	
(SELECT l2.INV_NUM,l2.LINE_NUM,l2.PROD_SKU,p2.PROD_DESCRIPT,p2.BRAND_ID 
FROM LINE l2,PRODUCT p2
WHERE l2.PROD_SKU = p2.PROD_SKU
AND p2.PROD_CATEGORY = 'TOP COAT'
) TOP_COAT
WHERE SEALER.INV_NUM = TOP_COAT.INV_NUM 
AND SEALER.BRAND_ID = TOP_COAT.BRAND_ID
;

--- query 4 ---

SELECT A.emp_id, 
y.EMP_FNAME,y.EMP_LNAME,y.EMP_EMAIL,A.units_sold
FROM
(
SELECT i.EMPLOYEE_ID, SUM(l.line_qty)
FROM
INVOICE i LEFT JOIN LINE l
ON i.INV_NUM = l.INV_NUM
LEFT JOIN PRODUCT P 
ON p.PROD_SKU = l.PROD_SKU
LEFT JOIN 
BRAND b ON b.BRAND_ID = p.BRAND_ID
WHERE b.BRAND_NAME = 'BINDER PRIME' and i.INV_DATE BETWEEN '2013-11-01' and '2013-12-05'
GROUP BY i.employee_id
) AS A
LEFT JOIN EMPLOYEE B
on A.EMP_ID = B.EMP_NUM;


--- query 5 -----
SELECT * FROM 
(SELECT c.CUST_CODE, c.CUST_FNAME, c.CUST_LNAME
FROM CUSTOMER c,INVOICE i
WHERE i.EMPLOYEE_ID = 83649 
AND c.CUST_CODE = i.CUST_CODE)
INTERSECT
(SELECT c1.CUST_CODE, c1.CUST_FNAME, c1.CUST_LNAME FROM CUSTOMER c1,invoice i1
WHERE i1.EMPLOYEE_ID = 83677
AND c1.CUST_CODE = i1.CUST_CODE)
ORDER BY 3,2;

----------DIAGNOSIS----------------
SELECT CUST_CODE FROM 
(SELECT  c.CUST_CODE,MAX(I.INV_TOTAL)
FROM CUSTOMER C LEFT JOIN INVOICE i ON c.CUST_CODE = i.CUST_CODE
WHERE c.CUST_STATE = 'AL'
GROUP BY C.CUST_CODE)
MINUS
SELECT CUST_CODE FROM(
SELECT c.CUST_CODE, c.CUST_FNAME, c.CUST_LNAME,c.CUST_STREET,
c.CUST_CITY,c.CUST_STATE,c.CUST_ZIP,i.INV_DATE,COALESCE(i.INV_TOTAL,0)
FROM  CUSTOMER C LEFT JOIN INVOICE i ON c.CUST_CODE = i.CUST_CODE
WHERE c.CUST_STATE = 'AL'
AND (c.CUST_CODE,I.INV_TOTAL) IN
(
SELECT  c.CUST_CODE,MAX(I.INV_TOTAL)
FROM CUSTOMER C LEFT JOIN INVOICE i ON c.CUST_CODE = i.CUST_CODE
WHERE c.CUST_STATE = 'AL'
GROUP BY C.CUST_CODE
));

SELECT * FROM CUSTOMER WHERE CUST_CODE=393;
SELECT * FROM INVOICE WHERE CUST_CODE=89;

---------------qUERY 6-----------------
SELECT * FROM 
(SELECT c.CUST_CODE, c.CUST_FNAME, c.CUST_LNAME,c.CUST_STREET,
c.CUST_CITY,c.CUST_STATE,c.CUST_ZIP,i.INV_DATE,COALESCE(i.INV_TOTAL,0) AS INV_TOTAL
FROM  CUSTOMER C LEFT JOIN INVOICE i ON c.CUST_CODE = i.CUST_CODE
WHERE c.CUST_STATE = 'AL') A
WHERE (A.CUST_CODE,A.INV_TOTAL) IN
(
SELECT  c.CUST_CODE,NVL(MAX(I.INV_TOTAL),0)
FROM CUSTOMER c LEFT JOIN INVOICE i ON c.CUST_CODE = i.CUST_CODE
WHERE c.CUST_STATE = 'AL'
GROUP BY c.CUST_CODE
);


--QUERY 7 ---

SELECT A.BRAND_ID, B.BRAND_NAME, B.BRAND_TYPE
,A.AVG_PROD_PRICE,B.TOT_UNIT_SOLD 
FROM ((SELECT b.BRAND_ID,ROUND(AVG(p.PROD_PRICE),4) AS AVG_PROD_PRICE 
FROM PRODUCT p,BRAND b
WHERE p.BRAND_ID = b.BRAND_ID 
GROUP BY b.BRAND_ID) A 
INNER JOIN (SELECT b1.BRAND_ID,b1.BRAND_NAME,b1.BRAND_TYPE,
SUM(l.LINE_QTY) AS TOT_UNIT_SOLD 
FROM LINE l ,PRODUCT p1 ,BRAND b1 
WHERE b1.BRAND_ID = p1.BRAND_ID AND p1.PROD_SKU=l.PROD_SKU 
GROUP BY b1.BRAND_ID,b1.BRAND_NAME,b1.BRAND_TYPE) B 
ON A.BRAND_ID=B.BRAND_ID);


SELECT CUST_CODE, INV_TOTAL FROM INVOICE I,J WHERE I.CUST_CODE = J.CUST_;

---INSERT INTO INVOICE VALUES (3455,'17-JAN-14',89,306.71,83649);

--- query 8---
SELECT b.BRAND_ID, b.BRAND_NAME,b.BRAND_TYPE,p.PROD_SKU,
p.PROD_DESCRIPT,p.PROD_PRICE 
FROM BRAND b,PRODUCT p
WHERE b.BRAND_ID=p.BRAND_ID
AND b.BRAND_TYPE <> 'PREMIUM'
AND p.PROD_PRICE > ANY 
( SELECT MAX(p.PROD_PRICE) 
FROM PRODUCT p1,BRAND b1 
WHERE p1.BRAND_ID = b1.BRAND_ID 
AND b1.BRAND_TYPE = 'PREMIUM'
GROUP BY b1.BRAND_ID);

--- query 9 ---
SELECT p.PROD_SKU,p.PROD_DESCRIPT,p.PROD_PRICE
FROM PRODUCT p
WHERE p.PROD_PRICE > 50
ORDER BY 1;

SELECT SUM(p.PROD_PRICE * p.PROD_QOH)
FROM PRODUCT p;

SELECT COUNT(c.CUST_CODE),SUM(c.CUST_BALANCE)
FROM CUSTOMER c;

SELECT * FROM (SELECT c.CUST_STATE, SUM(i.INV_TOTAL)
FROM CUSTOMER c LEFT JOIN INVOICE i
ON i.CUST_CODE = c.CUST_CODE
GROUP BY c.CUST_STATE
ORDER BY 2 DESC) 
WHERE ROWNUM <= 3;







